from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.product import Product
from swagger_server import util

from swagger_server.models.product import Product  # noqa: E501

class ApiProductsProductIdGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product=None):  # noqa: E501
        """ApiProductsProductIdGet200Response - a model defined in OpenAPI

        :param product: The product of this ApiProductsProductIdGet200Response.  # noqa: E501
        :type product: Product
        """
        self.openapi_types = {
            'product': Product
        }

        self.attribute_map = {
            'product': 'product'
        }

        self._product = product

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsProductIdGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products__product_id__get_200_response of this ApiProductsProductIdGet200Response.  # noqa: E501
        :rtype: ApiProductsProductIdGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product(self) -> Product:
        """Gets the product of this ApiProductsProductIdGet200Response.


        :return: The product of this ApiProductsProductIdGet200Response.
        :rtype: Product
        """
        return self._product

    @product.setter
    def product(self, product: Product):
        """Sets the product of this ApiProductsProductIdGet200Response.


        :param product: The product of this ApiProductsProductIdGet200Response.
        :type product: Product
        """

        self._product = product
