from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.product import Product
from swagger_server import util

from swagger_server.models.product import Product  # noqa: E501

class ApiProductsProductIdPut200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, product=None):  # noqa: E501
        """ApiProductsProductIdPut200Response - a model defined in OpenAPI

        :param message: The message of this ApiProductsProductIdPut200Response.  # noqa: E501
        :type message: str
        :param product: The product of this ApiProductsProductIdPut200Response.  # noqa: E501
        :type product: Product
        """
        self.openapi_types = {
            'message': str,
            'product': Product
        }

        self.attribute_map = {
            'message': 'message',
            'product': 'product'
        }

        self._message = message
        self._product = product

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsProductIdPut200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products__product_id__put_200_response of this ApiProductsProductIdPut200Response.  # noqa: E501
        :rtype: ApiProductsProductIdPut200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ApiProductsProductIdPut200Response.


        :return: The message of this ApiProductsProductIdPut200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ApiProductsProductIdPut200Response.


        :param message: The message of this ApiProductsProductIdPut200Response.
        :type message: str
        """

        self._message = message

    @property
    def product(self) -> Product:
        """Gets the product of this ApiProductsProductIdPut200Response.


        :return: The product of this ApiProductsProductIdPut200Response.
        :rtype: Product
        """
        return self._product

    @product.setter
    def product(self, product: Product):
        """Sets the product of this ApiProductsProductIdPut200Response.


        :param product: The product of this ApiProductsProductIdPut200Response.
        :type product: Product
        """

        self._product = product
