from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.api_products_product_id_delete200_response_deleted_product import ApiProductsProductIdDelete200ResponseDeletedProduct
from swagger_server import util

from swagger_server.models.api_products_product_id_delete200_response_deleted_product import ApiProductsProductIdDelete200ResponseDeletedProduct  # noqa: E501

class ApiProductsProductIdDelete200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, deleted_product=None):  # noqa: E501
        """ApiProductsProductIdDelete200Response - a model defined in OpenAPI

        :param message: The message of this ApiProductsProductIdDelete200Response.  # noqa: E501
        :type message: str
        :param deleted_product: The deleted_product of this ApiProductsProductIdDelete200Response.  # noqa: E501
        :type deleted_product: ApiProductsProductIdDelete200ResponseDeletedProduct
        """
        self.openapi_types = {
            'message': str,
            'deleted_product': ApiProductsProductIdDelete200ResponseDeletedProduct
        }

        self.attribute_map = {
            'message': 'message',
            'deleted_product': 'deleted_product'
        }

        self._message = message
        self._deleted_product = deleted_product

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsProductIdDelete200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products__product_id__delete_200_response of this ApiProductsProductIdDelete200Response.  # noqa: E501
        :rtype: ApiProductsProductIdDelete200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ApiProductsProductIdDelete200Response.


        :return: The message of this ApiProductsProductIdDelete200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ApiProductsProductIdDelete200Response.


        :param message: The message of this ApiProductsProductIdDelete200Response.
        :type message: str
        """

        self._message = message

    @property
    def deleted_product(self) -> ApiProductsProductIdDelete200ResponseDeletedProduct:
        """Gets the deleted_product of this ApiProductsProductIdDelete200Response.


        :return: The deleted_product of this ApiProductsProductIdDelete200Response.
        :rtype: ApiProductsProductIdDelete200ResponseDeletedProduct
        """
        return self._deleted_product

    @deleted_product.setter
    def deleted_product(self, deleted_product: ApiProductsProductIdDelete200ResponseDeletedProduct):
        """Sets the deleted_product of this ApiProductsProductIdDelete200Response.


        :param deleted_product: The deleted_product of this ApiProductsProductIdDelete200Response.
        :type deleted_product: ApiProductsProductIdDelete200ResponseDeletedProduct
        """

        self._deleted_product = deleted_product
