from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class ApiProductsPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, price=None, category=None, stock=None):  # noqa: E501
        """ApiProductsPostRequest - a model defined in OpenAPI

        :param name: The name of this ApiProductsPostRequest.  # noqa: E501
        :type name: str
        :param description: The description of this ApiProductsPostRequest.  # noqa: E501
        :type description: str
        :param price: The price of this ApiProductsPostRequest.  # noqa: E501
        :type price: float
        :param category: The category of this ApiProductsPostRequest.  # noqa: E501
        :type category: str
        :param stock: The stock of this ApiProductsPostRequest.  # noqa: E501
        :type stock: int
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'price': float,
            'category': str,
            'stock': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'category': 'category',
            'stock': 'stock'
        }

        self._name = name
        self._description = description
        self._price = price
        self._category = category
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products_post_request of this ApiProductsPostRequest.  # noqa: E501
        :rtype: ApiProductsPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ApiProductsPostRequest.


        :return: The name of this ApiProductsPostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ApiProductsPostRequest.


        :param name: The name of this ApiProductsPostRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ApiProductsPostRequest.


        :return: The description of this ApiProductsPostRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ApiProductsPostRequest.


        :param description: The description of this ApiProductsPostRequest.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ApiProductsPostRequest.


        :return: The price of this ApiProductsPostRequest.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ApiProductsPostRequest.


        :param price: The price of this ApiProductsPostRequest.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def category(self) -> str:
        """Gets the category of this ApiProductsPostRequest.


        :return: The category of this ApiProductsPostRequest.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this ApiProductsPostRequest.


        :param category: The category of this ApiProductsPostRequest.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def stock(self) -> int:
        """Gets the stock of this ApiProductsPostRequest.


        :return: The stock of this ApiProductsPostRequest.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this ApiProductsPostRequest.


        :param stock: The stock of this ApiProductsPostRequest.
        :type stock: int
        """

        self._stock = stock
