from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class ApiProductsProductIdDelete200ResponseDeletedProduct(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product_id=None, name=None):  # noqa: E501
        """ApiProductsProductIdDelete200ResponseDeletedProduct - a model defined in OpenAPI

        :param product_id: The product_id of this ApiProductsProductIdDelete200ResponseDeletedProduct.  # noqa: E501
        :type product_id: int
        :param name: The name of this ApiProductsProductIdDelete200ResponseDeletedProduct.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'product_id': int,
            'name': str
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'name': 'name'
        }

        self._product_id = product_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsProductIdDelete200ResponseDeletedProduct':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products__product_id__delete_200_response_deleted_product of this ApiProductsProductIdDelete200ResponseDeletedProduct.  # noqa: E501
        :rtype: ApiProductsProductIdDelete200ResponseDeletedProduct
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> int:
        """Gets the product_id of this ApiProductsProductIdDelete200ResponseDeletedProduct.


        :return: The product_id of this ApiProductsProductIdDelete200ResponseDeletedProduct.
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: int):
        """Sets the product_id of this ApiProductsProductIdDelete200ResponseDeletedProduct.


        :param product_id: The product_id of this ApiProductsProductIdDelete200ResponseDeletedProduct.
        :type product_id: int
        """

        self._product_id = product_id

    @property
    def name(self) -> str:
        """Gets the name of this ApiProductsProductIdDelete200ResponseDeletedProduct.


        :return: The name of this ApiProductsProductIdDelete200ResponseDeletedProduct.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ApiProductsProductIdDelete200ResponseDeletedProduct.


        :param name: The name of this ApiProductsProductIdDelete200ResponseDeletedProduct.
        :type name: str
        """

        self._name = name
