from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.product import Product
from swagger_server import util

from swagger_server.models.product import Product  # noqa: E501

class ApiProductsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, products=None):  # noqa: E501
        """ApiProductsGet200Response - a model defined in OpenAPI

        :param total: The total of this ApiProductsGet200Response.  # noqa: E501
        :type total: int
        :param products: The products of this ApiProductsGet200Response.  # noqa: E501
        :type products: List[Product]
        """
        self.openapi_types = {
            'total': int,
            'products': List[Product]
        }

        self.attribute_map = {
            'total': 'total',
            'products': 'products'
        }

        self._total = total
        self._products = products

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProductsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_products_get_200_response of this ApiProductsGet200Response.  # noqa: E501
        :rtype: ApiProductsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this ApiProductsGet200Response.


        :return: The total of this ApiProductsGet200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this ApiProductsGet200Response.


        :param total: The total of this ApiProductsGet200Response.
        :type total: int
        """

        self._total = total

    @property
    def products(self) -> List[Product]:
        """Gets the products of this ApiProductsGet200Response.


        :return: The products of this ApiProductsGet200Response.
        :rtype: List[Product]
        """
        return self._products

    @products.setter
    def products(self, products: List[Product]):
        """Sets the products of this ApiProductsGet200Response.


        :param products: The products of this ApiProductsGet200Response.
        :type products: List[Product]
        """

        self._products = products
