from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class AuthChangePasswordPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, old_password=None, new_password=None):  # noqa: E501
        """AuthChangePasswordPostRequest - a model defined in OpenAPI

        :param old_password: The old_password of this AuthChangePasswordPostRequest.  # noqa: E501
        :type old_password: str
        :param new_password: The new_password of this AuthChangePasswordPostRequest.  # noqa: E501
        :type new_password: str
        """
        self.openapi_types = {
            'old_password': str,
            'new_password': str
        }

        self.attribute_map = {
            'old_password': 'old_password',
            'new_password': 'new_password'
        }

        self._old_password = old_password
        self._new_password = new_password

    @classmethod
    def from_dict(cls, dikt) -> 'AuthChangePasswordPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_change_password_post_request of this AuthChangePasswordPostRequest.  # noqa: E501
        :rtype: AuthChangePasswordPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def old_password(self) -> str:
        """Gets the old_password of this AuthChangePasswordPostRequest.


        :return: The old_password of this AuthChangePasswordPostRequest.
        :rtype: str
        """
        return self._old_password

    @old_password.setter
    def old_password(self, old_password: str):
        """Sets the old_password of this AuthChangePasswordPostRequest.


        :param old_password: The old_password of this AuthChangePasswordPostRequest.
        :type old_password: str
        """
        if old_password is None:
            raise ValueError("Invalid value for `old_password`, must not be `None`")  # noqa: E501

        self._old_password = old_password

    @property
    def new_password(self) -> str:
        """Gets the new_password of this AuthChangePasswordPostRequest.


        :return: The new_password of this AuthChangePasswordPostRequest.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this AuthChangePasswordPostRequest.


        :param new_password: The new_password of this AuthChangePasswordPostRequest.
        :type new_password: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password
