from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class AuthRegisterPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None, email=None, full_name=None):  # noqa: E501
        """AuthRegisterPostRequest - a model defined in OpenAPI

        :param username: The username of this AuthRegisterPostRequest.  # noqa: E501
        :type username: str
        :param password: The password of this AuthRegisterPostRequest.  # noqa: E501
        :type password: str
        :param email: The email of this AuthRegisterPostRequest.  # noqa: E501
        :type email: str
        :param full_name: The full_name of this AuthRegisterPostRequest.  # noqa: E501
        :type full_name: str
        """
        self.openapi_types = {
            'username': str,
            'password': str,
            'email': str,
            'full_name': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'email': 'email',
            'full_name': 'full_name'
        }

        self._username = username
        self._password = password
        self._email = email
        self._full_name = full_name

    @classmethod
    def from_dict(cls, dikt) -> 'AuthRegisterPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_register_post_request of this AuthRegisterPostRequest.  # noqa: E501
        :rtype: AuthRegisterPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this AuthRegisterPostRequest.


        :return: The username of this AuthRegisterPostRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this AuthRegisterPostRequest.


        :param username: The username of this AuthRegisterPostRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this AuthRegisterPostRequest.


        :return: The password of this AuthRegisterPostRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this AuthRegisterPostRequest.


        :param password: The password of this AuthRegisterPostRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self) -> str:
        """Gets the email of this AuthRegisterPostRequest.


        :return: The email of this AuthRegisterPostRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this AuthRegisterPostRequest.


        :param email: The email of this AuthRegisterPostRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def full_name(self) -> str:
        """Gets the full_name of this AuthRegisterPostRequest.


        :return: The full_name of this AuthRegisterPostRequest.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this AuthRegisterPostRequest.


        :param full_name: The full_name of this AuthRegisterPostRequest.
        :type full_name: str
        """
        if full_name is None:
            raise ValueError("Invalid value for `full_name`, must not be `None`")  # noqa: E501

        self._full_name = full_name
