from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.user import User
from swagger_server import util

from swagger_server.models.user import User  # noqa: E501

class AuthMeGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None):  # noqa: E501
        """AuthMeGet200Response - a model defined in OpenAPI

        :param user: The user of this AuthMeGet200Response.  # noqa: E501
        :type user: User
        """
        self.openapi_types = {
            'user': User
        }

        self.attribute_map = {
            'user': 'user'
        }

        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'AuthMeGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_me_get_200_response of this AuthMeGet200Response.  # noqa: E501
        :rtype: AuthMeGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this AuthMeGet200Response.


        :return: The user of this AuthMeGet200Response.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this AuthMeGet200Response.


        :param user: The user of this AuthMeGet200Response.
        :type user: User
        """

        self._user = user
