from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class AuthLogoutPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, refresh_token=None):  # noqa: E501
        """AuthLogoutPostRequest - a model defined in OpenAPI

        :param refresh_token: The refresh_token of this AuthLogoutPostRequest.  # noqa: E501
        :type refresh_token: str
        """
        self.openapi_types = {
            'refresh_token': str
        }

        self.attribute_map = {
            'refresh_token': 'refresh_token'
        }

        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'AuthLogoutPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_logout_post_request of this AuthLogoutPostRequest.  # noqa: E501
        :rtype: AuthLogoutPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this AuthLogoutPostRequest.

        Optional refresh token to revoke  # noqa: E501

        :return: The refresh_token of this AuthLogoutPostRequest.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this AuthLogoutPostRequest.

        Optional refresh token to revoke  # noqa: E501

        :param refresh_token: The refresh_token of this AuthLogoutPostRequest.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
