from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server.models.user import User
from swagger_server import util

from swagger_server.models.user import User  # noqa: E501

class LoginResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, access_token=None, refresh_token=None, token_type=None, expires_in=None, user=None):  # noqa: E501
        """LoginResponse - a model defined in OpenAPI

        :param message: The message of this LoginResponse.  # noqa: E501
        :type message: str
        :param access_token: The access_token of this LoginResponse.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this LoginResponse.  # noqa: E501
        :type refresh_token: str
        :param token_type: The token_type of this LoginResponse.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this LoginResponse.  # noqa: E501
        :type expires_in: int
        :param user: The user of this LoginResponse.  # noqa: E501
        :type user: User
        """
        self.openapi_types = {
            'message': str,
            'access_token': str,
            'refresh_token': str,
            'token_type': str,
            'expires_in': int,
            'user': User
        }

        self.attribute_map = {
            'message': 'message',
            'access_token': 'access_token',
            'refresh_token': 'refresh_token',
            'token_type': 'token_type',
            'expires_in': 'expires_in',
            'user': 'user'
        }

        self._message = message
        self._access_token = access_token
        self._refresh_token = refresh_token
        self._token_type = token_type
        self._expires_in = expires_in
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this LoginResponse.


        :return: The message of this LoginResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this LoginResponse.


        :param message: The message of this LoginResponse.
        :type message: str
        """

        self._message = message

    @property
    def access_token(self) -> str:
        """Gets the access_token of this LoginResponse.


        :return: The access_token of this LoginResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this LoginResponse.


        :param access_token: The access_token of this LoginResponse.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this LoginResponse.


        :return: The refresh_token of this LoginResponse.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this LoginResponse.


        :param refresh_token: The refresh_token of this LoginResponse.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this LoginResponse.


        :return: The token_type of this LoginResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this LoginResponse.


        :param token_type: The token_type of this LoginResponse.
        :type token_type: str
        """

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this LoginResponse.


        :return: The expires_in of this LoginResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this LoginResponse.


        :param expires_in: The expires_in of this LoginResponse.
        :type expires_in: int
        """

        self._expires_in = expires_in

    @property
    def user(self) -> User:
        """Gets the user of this LoginResponse.


        :return: The user of this LoginResponse.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this LoginResponse.


        :param user: The user of this LoginResponse.
        :type user: User
        """

        self._user = user
