from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model import Model
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product_id=None, name=None, description=None, price=None, category=None, stock=None, created_by=None, created_at=None, updated_at=None):  # noqa: E501
        """Product - a model defined in OpenAPI

        :param product_id: The product_id of this Product.  # noqa: E501
        :type product_id: int
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param description: The description of this Product.  # noqa: E501
        :type description: str
        :param price: The price of this Product.  # noqa: E501
        :type price: float
        :param category: The category of this Product.  # noqa: E501
        :type category: str
        :param stock: The stock of this Product.  # noqa: E501
        :type stock: int
        :param created_by: The created_by of this Product.  # noqa: E501
        :type created_by: int
        :param created_at: The created_at of this Product.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Product.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'product_id': int,
            'name': str,
            'description': str,
            'price': float,
            'category': str,
            'stock': int,
            'created_by': int,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'category': 'category',
            'stock': 'stock',
            'created_by': 'created_by',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._product_id = product_id
        self._name = name
        self._description = description
        self._price = price
        self._category = category
        self._stock = stock
        self._created_by = created_by
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> int:
        """Gets the product_id of this Product.


        :return: The product_id of this Product.
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: int):
        """Sets the product_id of this Product.


        :param product_id: The product_id of this Product.
        :type product_id: int
        """

        self._product_id = product_id

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Product.


        :return: The description of this Product.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Product.


        :param description: The description of this Product.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this Product.


        :return: The price of this Product.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Product.


        :param price: The price of this Product.
        :type price: float
        """

        self._price = price

    @property
    def category(self) -> str:
        """Gets the category of this Product.


        :return: The category of this Product.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Product.


        :param category: The category of this Product.
        :type category: str
        """

        self._category = category

    @property
    def stock(self) -> int:
        """Gets the stock of this Product.


        :return: The stock of this Product.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this Product.


        :param stock: The stock of this Product.
        :type stock: int
        """

        self._stock = stock

    @property
    def created_by(self) -> int:
        """Gets the created_by of this Product.


        :return: The created_by of this Product.
        :rtype: int
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: int):
        """Sets the created_by of this Product.


        :param created_by: The created_by of this Product.
        :type created_by: int
        """

        self._created_by = created_by

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Product.


        :return: The created_at of this Product.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Product.


        :param created_at: The created_at of this Product.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Product.


        :return: The updated_at of this Product.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Product.


        :param updated_at: The updated_at of this Product.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
